### PR TITLE
Fix37

### LINKED ISSUE #37: OpenCL calls broken in 10.0.2
In 10.0.2 using OpenCL created these issues
```
ERROR: clEnqueueWriteBuffer clErrorCode -36
ERROR: clEnqueueNDRangeKernel clErrorCode -36
ERROR: clEnqueueReadBuffer clErrorCode -36
```

these were tracked down to the "throw" clean-up commit 86480c5f015eff0600d6c572a8661d2910a533d6 that unfortunately has "eaten up" some mandatory cmdQueue initialization in CLBuffer and CLKernel 
here https://github.com/iclcv/icl/commit/86480c5f015eff0600d6c572a8661d2910a533d6#diff-e0563068c6edf61678b0902384130972L76
and here
https://github.com/iclcv/icl/commit/86480c5f015eff0600d6c572a8661d2910a533d6#diff-618ef9bd1e6c0ebc09f73e62ac7eb9b2L49

a PR will be done with a fix

there might be other "eaten-up" commands depending if the clean-up was automatized and ignored any commands after the closing parenthesis of the throw.

### PR DESCRIPTION
**Pull request by guihomework**
fixes #37

### CODE REVIEW

**Comment by guihomework** [comment]
sorry for the force push, thought a little late to rename the debug output a little more consistently (and also removed a verbose matrix display)

**Comment by rhaschke** [comment]
I found several other issues with 86480c5. @aleneum, let's discuss tomorrow how to cleanly handle this.
I prepared a fixed branch (`rhaschke-master`).

**Comment by aleneum** [comment]
canceled ci builds in favor of #39

**Comment by aleneum** [comment]
closed in favor of #39

**Pull request closed without merging**
