### PR TITLE
[WIP] Non ancient opencv

### PR DESCRIPTION
**Pull request by LeroyR**
I updated ICLCore and ICLIO to use c++ opencv API (10 years old) instead of the (in opencv4 finally) removed c API (having to import  c header like imgproc_c.h), thinking that should be all.

(hint: its not)
I rather replace ICL than migrate more code but maybe it helps someone to finish this

### CODE REVIEW

**Comment by aleneum** [comment]
Hey @LeroyR, 

thank you for giving this a try. I agree that it feels like to open a can of worms. AppVeyor build errors are easy to solve since this is just the Qt5 dependency being a moving target on windows. However, it seems like you removed more flags than required according to the travis build job.

**Comment by LeroyR** [comment]
What do you mean by flags?

ICLCV is not building as i did stop migration at that point.

Yes this removes some Functions using Symbols from OpenCVs C API that have no place in any c++ library since 10 years ago thus breaking the untouched parts.

**Comment by aleneum** [comment]
I misread the travis errors as IPP issues and assumed some IPP functions are leaking but its the 'IPL problem' I faced as well when I tried to update ICL (thats why I filed #31).  I'd guess it takes some deeper knowledge of the ICL than I have to replace the IPLImage compatibility layer with a more recent functionality. Whether time and resources can be assigned to this issue probably depends on @rhaschke's and/or @guihomework's future ICL application plans. @celbrech and @scires probably also have the knowledge and skills to tackle this issue but I'd guess both lack time and incentives to do so as they have moved on to other duties.

**Comment by rhaschke** [comment]
I merged these commits into #45, a forwarded `dev-opencv` branch.

**Pull request closed without merging**
